"""Keep the homepage's first paint independent of stylesheet round trips."""
from pathlib import Path
import re

root = Path(__file__).resolve().parent.parent
page = root / 'index.html'
start = '<!-- Homepage styles: generated by scripts/embed-home-styles.py -->'
end = '<!-- End homepage styles -->'
css = '\n'.join((root / name).read_text() for name in ('styles.css', 'sound.css', 'partners.css'))
block = f'{start}\n<style id="home-styles">\n{css}\n</style>\n{end}'
html = page.read_text()
if start in html:
    html = re.sub(re.escape(start) + r'.*?' + re.escape(end), lambda _: block, html, flags=re.S)
else:
    html = re.sub(r'<link rel="stylesheet" href="(?:styles|sound|partners)\.css[^"\n]*">\n?', '', html)
    html = html.replace('<link rel="canonical"', block + '\n<link rel="canonical"', 1)
page.write_text(html)
